### ISSUE TITLE
scan.csv review

### ISSUE THREAD

**Issue by maoo** [finos-labs/project-analysis#37]
@robmoffat - checked this with @TheJuanAndOnly99 , this is the recap we came up with:
- [landscape.yml](https://github.com/finos/finos-landscape/blob/master/landscape.yml) should be used to pull projects and repositories
- the list should be made of github repositories (as it is right now), but adding a `project name` column, that can be used to group results by project.
- add a column called `type`, which can be either `SIG` or `Project` (depending on the value of the `project` field in landscape.yml ; obviously, the value of this field for all repos of the same project will be the same
- add a column called `stage`, which can be either null (for SIGs, who don't have a stage), `Active` or `Incubating` (reflecting the stage of a project); note that archived projects are not listed here.
- Each project should define a primary repository, which is where the README would get pulled from for parsing

I feel that these changes should not be very hard to apply on code; and when that's done, we can regenerate the page and see where we land; finally, if you're ok, we can automate the running and publishing by pushing changes into github.com/finos (using a GitHub Personal Access Token).

Eager to hear your thoughts!

**Comment by robmoffat** [comment]
Yep, this is awesome feedback. I'll get on it.

**Comment by maoo** [comment]
@robmoffat - based on further conversations with the TOC , I mave some changes on the description above, specifically:

- [landscape.yml](https://github.com/finos/finos-landscape/blob/master/landscape.yml) should be used to pull projects and repositories
- the list should be made of github repositories (as it is right now), but adding a `project name` column, that can be used to group results by project.
- add a column called `type`, which can be either `SIG` or `Project` (depending on the value of the `project` field in landscape.yml ; obviously, the value of this field for all repos of the same project will be the same
- add a column called `stage`, which can be either null (for SIGs, who don't have a stage), `Active` or `Incubating` (reflecting the stage of a project); note that archived projects are not listed here.

**Comment by maoo** [comment]
> Just wanted to check - this Issue is called README review, but I think you're referring to the scan.csv file report, right?

Correct

**Comment by maoo** [comment]
I think all items were addressed. Closing issue.
